fecha_nacimiento = input("Por favor, introduce tu fecha de nacimiento en formato dd/mm/aaaa: ")
dia, mes, anio = fecha_nacimiento.split('/')
print(f"Día: {dia}")
print(f"Mes: {mes}")
print(f"Año: {anio}")